# Application
spring.application.name=taskflow-api
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/taskflow_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logging
logging.level.com.taskflow=DEBUG
logging.level.org.springframework.web=INFO

# Disable open-in-view ? prevents lazy loading issues and hides the warning
spring.jpa.open-in-view=false

# JWT
# Secret key ? must be at least 256 bits (32 characters) for HS256
# In production this comes from environment variables ? never hardcode
jwt.secret=taskflow-super-secret-key-for-jwt-signing-2024
jwt.expiration=86400000
# 86400000ms = 24 hours

